DROP SCHEMA BDHOTEL;
CREATE SCHEMA IF NOT EXISTS `BDHOTEL` DEFAULT CHARACTER SET utf8 ;
USE `BDHOTEL` ;

CREATE TABLE IF NOT EXISTS `BDHOTEL`.`CLIENTE` (
  `ID` SMALLINT NOT NULL,
  `NOME` VARCHAR(45) NULL,
  `SOBRENOME` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`));




CREATE TABLE IF NOT EXISTS `BDHOTEL`.`HOTEL` (
  `QUARTO` CHAR(5) NOT NULL,
  `VALQTDIARIA` SMALLINT NULL,
  PRIMARY KEY (`QUARTO`));




CREATE TABLE IF NOT EXISTS `BDHOTEL`.`Hospedagem` (
  `ID` SMALLINT NOT NULL,
  `CHECKIN` DATE NOT NULL,
  `CHECKOUT` DATE NOT NULL,
  `DIARIAS` SMALLINT NULL,
  `VALTOTAL` INT NULL,
  `ID_CLIENTE` SMALLINT NOT NULL,
  `QUARTO` CHAR(5) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_CLIENTE_HOSPEDAGEM`
    FOREIGN KEY (`ID_CLIENTE`)
    REFERENCES `BDHOTEL`.`CLIENTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_HOTEL_HOSPEDAGEM`
    FOREIGN KEY (`QUARTO`)
    REFERENCES `BDHOTEL`.`HOTEL` (`QUARTO`));
